project:
  type: book

book:
  title: "Justin's AWS Notes"
  author: "Justin Shaw"
  date: "2025-10-28"
  chapters:
    - index.qmd
    - part: chapters/1-AWS-Fundamentals/1-AWS-Fundamentals.qmd
      chapters:
      - chapters/1-AWS-Fundamentals/1.1-Core-Concepts-&-Infrastructure.qmd


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



